apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fake-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      run: fake-blog
  template:
    metadata:
      labels:
        run: fake-blog
    spec:
      containers:
      - image: fake_blog:latest
        imagePullPolicy: IfNotPresent
        name: fake-blog
        env:
        - name: CONSUMER_KEY
          value: your-consumer-key-here
        - name: REDIRECT_HOST
          value: fakeblog.me
---
apiVersion: v1
kind: Service
metadata:
  name: fake-blog
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: fake-blog
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fake-blog
spec:
  rules:
  - host: fakeblog.me
    http:
      paths:
      - backend:
          serviceName: fake-blog
          servicePort: http
