apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fake-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      run: fake-blog
  template:
    metadata:
      labels:
        run: fake-blog
    spec:
      containers:
      - image: fake_blog:latest
        imagePullPolicy: IfNotPresent
        name: fake-blog
        env:
        - name: CONSUMER_KEY
          value: your-consumer-key-here
---
apiVersion: v1
kind: Service
metadata:
  name: fake-blog
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: fake-blog
  type: NodePort
